-- MySQL Script generated by MySQL Workbench
-- Mon May 27 22:06:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rhmais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rhmais
-- -----------------------------------------------------

CREATE SCHEMA
IF NOT EXISTS `rhmais` DEFAULT CHARACTER
SET utf8 ;
-- -----------------------------------------------------
-- Schema rhmais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rhmais
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `rhmais` DEFAULT CHARACTER
SET latin1 ;
USE `rhmais`
;

-- -----------------------------------------------------
-- Table `rhmais`.`instituicao_ensino`
-- -----------------------------------------------------
DROP TABLE `instituicao_ensino`
IF EXISTS;
CREATE TABLE
IF NOT EXISTS `rhmais`.`instituicao_ensino`
(
  `id_ensino` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR
(45) NULL,
  `cnpj` VARCHAR
(45) NULL,
  `insc_estadual` VARCHAR
(45) NULL,
  `mantenedora` VARCHAR
(45) NULL,
  `telefone` VARCHAR
(45) NULL,
  `nome_contato` VARCHAR
(45) NULL,
  `email_contato` VARCHAR
(45) NULL,
  `cel_representante` VARCHAR
(45) NULL,
  `rg_representante` VARCHAR
(45) NULL,
  `site_url` VARCHAR
(45) NULL,
  `celular_contato` VARCHAR
(45) NULL,
  `nome_representante` VARCHAR
(45) NULL,
  `cpf_representante` VARCHAR
(45) NULL,
  `email_representante` VARCHAR
(45) NULL,
  PRIMARY KEY
(`id_ensino`))
ENGINE = InnoDB
DEFAULT CHARACTER
SET = latin1;


-- -----------------------------------------------------
-- Table `rhmais`.`users`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`users`
(
  `id` INT
(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR
(255) NOT NULL,
  `email` VARCHAR
(255) NOT NULL,
  `email_verified_at` VARCHAR
(255) NOT NULL,
  `password` VARCHAR
(255) NOT NULL,
  `remember_token` VARCHAR
(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `rg` VARCHAR
(45) NULL,
  `cpf` VARCHAR
(45) NULL,
  `telefone` VARCHAR
(45) NULL,
  `celular` VARCHAR
(45) NULL,
  `dt_nascimento` DATE NULL,
  `sexo` VARCHAR
(45) NULL,
  `pai` VARCHAR
(45) NULL,
  `mae` VARCHAR
(45) NULL,
  PRIMARY KEY
(`id`),
  UNIQUE INDEX `users_email_unique`
(`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER
SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

INSERT INTO `
rhmais`.`users
`
(`id`, `nome`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
('1', 'Admin Admin', 'admin@argon.com', 'admin@argon.com', '$2y$10$05JdYoAWfF0AVR3UYGdqIuOD1gcvxtnNQtUzyTjOC1e/qoJGSX0gy', '1TnegvMfzWaSv3qC6S9E0bgTnAl6ZX5q30t1CHwJSs2f1nKT6BTtgRvApiDW', '2019-05-25 19:11:51', '2019-05-25 19:11:51');

-- -----------------------------------------------------
-- Table `rhmais`.`unidade_concedente`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`unidade_concedente`
(
  `id_unidade_concedente` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR
(45) NULL,
  `nome_fantasia` VARCHAR
(45) NULL,
  `cnpj_cpf` VARCHAR
(45) NULL,
  `insc_estadual` VARCHAR
(45) NULL,
  `telefone` VARCHAR
(45) NULL,
  `celular_contato` VARCHAR
(45) NULL,
  `nome_representante` VARCHAR
(45) NULL,
  `cpf_representante` VARCHAR
(45) NULL,
  `email_representante` VARCHAR
(45) NULL,
  `agente_intregacao` VARCHAR
(45) NULL,
  `celular` VARCHAR
(45) NULL,
  `nome_contato` VARCHAR
(45) NULL,
  `email_contato` VARCHAR
(45) NULL,
  `celular_representamte` VARCHAR
(45) NULL,
  `rg_representante` VARCHAR
(45) NULL,
  PRIMARY KEY
(`id_unidade_concedente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmais`.`endereco`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`endereco`
(
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR
(45) NULL,
  `numero` VARCHAR
(45) NULL,
  `bairro` VARCHAR
(45) NULL,
  `cidade` VARCHAR
(45) NULL,
  `estado` VARCHAR
(45) NULL,
  `cep` VARCHAR
(45) NULL,
  `complemento` VARCHAR
(45) NULL,
  `users_id` INT
(10) UNSIGNED NOT NULL,
  `instituicao_ensino_id_ensino` INT NOT NULL,
  `unidade_concedente_id_unidade_concedente` INT NOT NULL,
  PRIMARY KEY
(`id_endereco`),
  INDEX `fk_endereco_users_idx`
(`users_id` ASC),
  INDEX `fk_endereco_instituicao_ensino1_idx`
(`instituicao_ensino_id_ensino` ASC) ,
  INDEX `fk_endereco_unidade_concedente1_idx`
(`unidade_concedente_id_unidade_concedente` ASC) ,
  CONSTRAINT `fk_endereco_users`
    FOREIGN KEY
(`users_id`)
    REFERENCES `rhmais`.`users`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_instituicao_ensino1`
    FOREIGN KEY
(`instituicao_ensino_id_ensino`)
    REFERENCES `rhmais`.`instituicao_ensino`
(`id_ensino`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_unidade_concedente1`
    FOREIGN KEY
(`unidade_concedente_id_unidade_concedente`)
    REFERENCES `rhmais`.`unidade_concedente`
(`id_unidade_concedente`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmais`.`cobranca`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`cobranca`
(
  `id_cobranca` INT NOT NULL AUTO_INCREMENT,
  `dia_pg_estagio` DATE NULL,
  `dia_fechamento` DATE NULL,
  `cob_valor_fixo` VARCHAR
(45) NULL,
  `custo_unitario` FLOAT NULL,
  `proporcional` FLOAT NULL,
  `ativo` INT
(2) NULL,
  `dia_vcto_pg_boleto` DATE NULL,
  `quant_tce_plano` VARCHAR
(45) NULL,
  `valor_adicional` FLOAT NULL,
  `dias_comerciais` INT
(10) NULL,
  `roda_folha` VARCHAR
(45) NULL,
  `obs` TEXT
(200) NULL,
  PRIMARY KEY
(`id_cobranca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmais`.`estagiario`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`estagiario`
(
  `id_estagiario` INT NOT NULL AUTO_INCREMENT,
  `serie_ctps` VARCHAR
(45) NULL,
  `dt_nascimento` DATE NULL,
  `cor_raca` VARCHAR
(45) NULL,
  `dt_cadastro` DATE NULL,
  `unid_concedente` VARCHAR
(45) NULL,
  `agente_int` VARCHAR
(45) NULL,
  `ctps` VARCHAR
(45) NULL,
  `numero_pis` VARCHAR
(45) NULL,
  `pessoal_responsavel` VARCHAR
(45) NULL,
  `users_id` INT
(10) UNSIGNED NOT NULL,
  `instituicao_ensino_id_ensino` INT NOT NULL,
  PRIMARY KEY
(`id_estagiario`),
  INDEX `fk_estagiario_users1_idx`
(`users_id` ASC) ,
  INDEX `fk_estagiario_instituicao_ensino1_idx`
(`instituicao_ensino_id_ensino` ASC) ,
  CONSTRAINT `fk_estagiario_users1`
    FOREIGN KEY
(`users_id`)
    REFERENCES `rhmais`.`users`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_estagiario_instituicao_ensino1`
    FOREIGN KEY
(`instituicao_ensino_id_ensino`)
    REFERENCES `rhmais`.`instituicao_ensino`
(`id_ensino`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmais`.`estagiario_has_unidade_concedente`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`estagiario_has_unidade_concedente`
(
  `estagiario_id_estagiario` INT NOT NULL,
  `unidade_concedente_id_unidade_concedente` INT NOT NULL,
  PRIMARY KEY
(`estagiario_id_estagiario`, `unidade_concedente_id_unidade_concedente`),
  INDEX `fk_estagiario_has_unidade_concedente_unidade_concedente1_idx`
(`unidade_concedente_id_unidade_concedente` ASC) ,
  INDEX `fk_estagiario_has_unidade_concedente_estagiario1_idx`
(`estagiario_id_estagiario` ASC) ,
  CONSTRAINT `fk_estagiario_has_unidade_concedente_estagiario1`
    FOREIGN KEY
(`estagiario_id_estagiario`)
    REFERENCES `rhmais`.`estagiario`
(`id_estagiario`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_estagiario_has_unidade_concedente_unidade_concedente1`
    FOREIGN KEY
(`unidade_concedente_id_unidade_concedente`)
    REFERENCES `rhmais`.`unidade_concedente`
(`id_unidade_concedente`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmais`.`unidade_concedente_has_cobranca`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`unidade_concedente_has_cobranca`
(
  `unidade_concedente_id_unidade_concedente` INT NOT NULL,
  `cobranca_id_cobranca` INT NOT NULL,
  PRIMARY KEY
(`unidade_concedente_id_unidade_concedente`, `cobranca_id_cobranca`),
  INDEX `fk_unidade_concedente_has_cobranca_cobranca1_idx`
(`cobranca_id_cobranca` ASC) ,
  INDEX `fk_unidade_concedente_has_cobranca_unidade_concedente1_idx`
(`unidade_concedente_id_unidade_concedente` ASC) ,
  CONSTRAINT `fk_unidade_concedente_has_cobranca_unidade_concedente1`
    FOREIGN KEY
(`unidade_concedente_id_unidade_concedente`)
    REFERENCES `rhmais`.`unidade_concedente`
(`id_unidade_concedente`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_concedente_has_cobranca_cobranca1`
    FOREIGN KEY
(`cobranca_id_cobranca`)
    REFERENCES `rhmais`.`cobranca`
(`id_cobranca`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

USE `rhmais`
;

-- -----------------------------------------------------
-- Table `rhmais`.`migrations`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`migrations`
(
  `id` INT
(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR
(255) NOT NULL,
  `batch` INT
(11) NOT NULL,
  PRIMARY KEY
(`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER
SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rhmais`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `rhmais`.`password_resets`
(
  `email` VARCHAR
(255) NOT NULL,
  `token` VARCHAR
(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index`
(`email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER
SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
